[build]
  publish = "."
  functions = "netlify/functions"

# Configuración del formulario
[[forms]]
  name = "comentarios"
  action = "/"
  
  [forms.handlers]
    [forms.handlers.background]
      function = "ClasificarComentarios"

# Redirecciones
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de funciones
[functions]
  node_bundler = "esbuild"